apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudops-hub.fullname" . }}
  labels:
    {{- include "cloudops-hub.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http

  selector:
    {{- include "cloudops-hub.selectorLabels" . | nindent 4 }}
