apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: cloudops-hub
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cloudops-hub
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
