apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cloudops-hub
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: cloudops-hub
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
