apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudops-hub
type: Opaque
stringData:
  POSTGRES_USER: cloudops
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: cloudops_hub
  DATABASE_URL: postgresql://cloudops:CHANGE_ME@postgres:5432/cloudops_hub
